<?php
require __DIR__.'/../bootstrap.php';

$db->executeQuery('CREATE TABLE IF NOT EXISTS user (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    name    TEXT NOT NULL,
    surname TEXT NOT NULL,
    address TEXT,
    email   TEXT
)');

$db->executeQuery('DELETE FROM user WHERE 1 = 1');

$users = [
    ["name"=>"Brigitta","surname"=>"Messina","address"=>"Incrocio Renzo 509 Sesto Giulietta, 11026 Alessandria (CN)","email"=>"Brigitta.Messina@yahoo.com"],
    ["name"=>"Edvige","surname"=>"Fiore","address"=>"Rotonda Fiore 82 Quarto Ruth nell'emilia, 95008 Pesaro e Urbino (BT)","email"=>"Edvige.Fiore@yahoo.com"],
    ["name"=>"Danuta","surname"=>"Barbieri","address"=>"Piazza Fernando 793 San Doriana veneto, 51631 Medio Campidano (OT)","email"=>"Danuta.Barbieri@yahoo.com"],
    ["name"=>"Gelsomina","surname"=>"Serra","address"=>"Via Fabbri 38 Piano 4 Longo laziale, 57202 Udine (CN)","email"=>"Gelsomina.Serra@yahoo.com"],
    ["name"=>"Mauro","surname"=>"Cattaneo","address"=>"Borgo Genziana 50 Settimo Ingrid, 41224 Como (PA)","email"=>"Mauro.Cattaneo@yahoo.com"],
    ["name"=>"Demian","surname"=>"Gentile","address"=>"Rotonda Marina 79 Maristella laziale, 44731 Pordenone (AG)","email"=>"Demian.Gentile@hotmail.com"],
    ["name"=>"Rosolino","surname"=>"Bianchi","address"=>"Strada Domiziano 39 Appartamento 98 Sibilla sardo, 72101 Teramo (VS)","email"=>"Rosolino.Bianchi@yahoo.com"],
    ["name"=>"Gelsomina","surname"=>"Orlando","address"=>"Incrocio Emanuel 38 Quarto Claudia salentino, 61257 Modena (TR)","email"=>"Gelsomina.Orlando@hotmail.com"],
    ["name"=>"Mirco","surname"=>"Ruggiero","address"=>"Via Monti 681 Piano 3 Bianco terme, 19265 Rovigo (OT)","email"=>"Mirco.Ruggiero@yahoo.com"],
    ["name"=>"Maika","surname"=>"Bianco","address"=>"Contrada Brigitta 6 Piano 8 Settimo Alberto veneto, 66712 Benevento (AQ)","email"=>"Maika.Bianco@yahoo.com"],
    ["name"=>"Sarita","surname"=>"Moretti","address"=>"Incrocio Luna 849 Borgo Ferdinando, 19322 Nuoro (CS)","email"=>"Sarita.Moretti@hotmail.com"],
    ["name"=>"Vitalba","surname"=>"Marchetti","address"=>"Piazza Samira 056 Borgo Costantino umbro, 67750 Novara (AL)","email"=>"Vitalba.Marchetti@hotmail.com"],
    ["name"=>"Ausonio","surname"=>"Battaglia","address"=>"Rotonda Eufemia 927 Piano 2 Villa umbro, 10872 Palermo (CT)","email"=>"Ausonio.Battaglia@hotmail.com"],
    ["name"=>"Lucrezia","surname"=>"Fabbri","address"=>"Incrocio De rosa 78 Appartamento 09 Pellegrini a mare, 12235 Bergamo (SP)","email"=>"Lucrezia.Fabbri@hotmail.com"],
    ["name"=>"Marieva","surname"=>"Bellini","address"=>"Incrocio Ivano 73 Bellini veneto, 47008 Parma (RG)","email"=>"Marieva.Bellini@hotmail.com"],
    ["name"=>"Edilio","surname"=>"Colombo","address"=>"Contrada Gatti 041 San Fernando, 23129 Medio Campidano (NO)","email"=>"Edilio.Colombo@yahoo.com"],
    ["name"=>"Dindo","surname"=>"Villa","address"=>"Strada Ubaldo 4 Appartamento 19 Guerra laziale, 71208 Brindisi (SV)","email"=>"Dindo.Villa@yahoo.com"],
    ["name"=>"Zelida","surname"=>"Russo","address"=>"Borgo Lamberto 37 Borgo Isabel, 37421 Gorizia (CO)","email"=>"Zelida.Russo@yahoo.com"],
    ["name"=>"Matteo","surname"=>"Valentini","address"=>"Via Cleros 2 Borgo Ruth, 83177 Bolzano (CH)","email"=>"Matteo.Valentini@hotmail.com"],
    ["name"=>"Gioacchino","surname"=>"Damico","address"=>"Strada De Angelis 590 Piano 0 Borgo Maria veneto, 50911 Enna (AQ)","email"=>"Gioacchino.Damico@yahoo.com"],
    ["name"=>"Iacopo","surname"=>"Mazza","address"=>"Piazza Barbieri 0 San Carmela umbro, 35683 Vibo Valentia (CH)","email"=>"Iacopo.Mazza@yahoo.com"],
    ["name"=>"Gianantonio","surname"=>"Montanari","address"=>"Via Battaglia 283 Settimo Cecco, 31057 Ravenna (UD)","email"=>"Gianantonio.Montanari@yahoo.com"],
    ["name"=>"Oreste","surname"=>"Bernardi","address"=>"Contrada Rizzo 576 San Marieva, 83013 Chieti (PG)","email"=>"Oreste.Bernardi@yahoo.com"],
    ["name"=>"Emilia","surname"=>"Pagano","address"=>"Rotonda Sabino 7 Piano 8 Settimo Sabatino, 38387 Agrigento (NO)","email"=>"Emilia.Pagano@yahoo.com"],
    ["name"=>"Michele","surname"=>"Russo","address"=>"Strada D'amico 0 Appartamento 47 Sesto Sarita, 29852 Caserta (LO)","email"=>"Michele.Russo@yahoo.com"],
    ["name"=>"Luce","surname"=>"Mariani","address"=>"Contrada De Angelis 367 Martinelli veneto, 80722 Reggio Calabria (SI)","email"=>"Luce.Mariani@yahoo.com"],
    ["name"=>"Rosaria","surname"=>"De Angelis","address"=>"Contrada Vitali 909 Quarto Mietta, 49576 Ancona (PC)","email"=>"Rosaria.De Angelis@yahoo.com"],
    ["name"=>"Giulietta","surname"=>"Sorrentino","address"=>"Piazza Conti 033 Piano 0 Caruso terme, 99875 Prato (RN)","email"=>"Giulietta.Sorrentino@yahoo.com"],
    ["name"=>"Shaira","surname"=>"Riva","address"=>"Via De luca 9 Piano 8 Settimo Elda nell'emilia, 81233 Pescara (BL)","email"=>"Shaira.Riva@hotmail.com"],
    ["name"=>"Trevis","surname"=>"Messina","address"=>"Contrada Rinaldi 75 Appartamento 24 Raoul nell'emilia, 30364 Napoli (PD)","email"=>"Trevis.Messina@yahoo.com"],
    ["name"=>"Maika","surname"=>"Carbone","address"=>"Contrada Clea 4 Appartamento 79 Vitalba del friuli, 86672 Matera (AT)","email"=>"Maika.Carbone@yahoo.com"],
    ["name"=>"Morgana","surname"=>"Orlando","address"=>"Piazza Marini 16 Maristella nell'emilia, 83229 Chieti (VI)","email"=>"Morgana.Orlando@hotmail.com"],
    ["name"=>"Mercedes","surname"=>"Rizzi","address"=>"Rotonda Amato 3 Piano 4 San Yago a mare, 04427 Bologna (VA)","email"=>"Mercedes.Rizzi@yahoo.com"],
    ["name"=>"Irene","surname"=>"Valentini","address"=>"Incrocio Galli 8 Borgo Edipo lido, 53655 Firenze (IS)","email"=>"Irene.Valentini@yahoo.com"],
    ["name"=>"Rosalba","surname"=>"Lombardi","address"=>"Via Cesidia 339 Giulio veneto, 69872 Crotone (CA)","email"=>"Rosalba.Lombardi@yahoo.com"],
    ["name"=>"Marieva","surname"=>"Conti","address"=>"Strada Pellegrino 73 Appartamento 23 Quarto Rosaria lido, 84722 Biella (LU)","email"=>"Marieva.Conti@yahoo.com"],
    ["name"=>"Cosetta","surname"=>"De rosa","address"=>"Incrocio Sirio 338 Borgo Pacifico, 02046 Aosta (BN)","email"=>"Cosetta.De rosa@yahoo.com"],
    ["name"=>"Ortensia","surname"=>"Bianchi","address"=>"Piazza Secondo 02 Piano 1 Guendalina del friuli, 78519 Campobasso (SI)","email"=>"Ortensia.Bianchi@yahoo.com"],
    ["name"=>"Monia","surname"=>"Grassi","address"=>"Strada Danuta 855 D'angelo sardo, 19117 Reggio Calabria (BG)","email"=>"Monia.Grassi@yahoo.com"],
    ["name"=>"Tazio","surname"=>"Colombo","address"=>"Via Giorgio 985 Karim salentino, 80267 Frosinone (TO)","email"=>"Tazio.Colombo@yahoo.com"],
    ["name"=>"Rufo","surname"=>"Costantini","address"=>"Via Grassi 07 Piano 7 Testa a mare, 35620 Lucca (SA)","email"=>"Rufo.Costantini@hotmail.com"],
    ["name"=>"Rosita","surname"=>"Caputo","address"=>"Strada Miriam 40 Settimo Mattia, 17691 Genova (TP)","email"=>"Rosita.Caputo@hotmail.com"],
    ["name"=>"Loretta","surname"=>"Santoro","address"=>"Rotonda Tazio 6 Piano 2 Silvestri veneto, 64779 Belluno (TN)","email"=>"Loretta.Santoro@yahoo.com"],
    ["name"=>"Silvano","surname"=>"Milani","address"=>"Via Gallo 418 Leone salentino, 01046 Pordenone (CN)","email"=>"Silvano.Milani@yahoo.com"],
    ["name"=>"Miriam","surname"=>"Negri","address"=>"Borgo Davis 575 Appartamento 34 Palmieri lido, 37000 Oristano (PG)","email"=>"Miriam.Negri@yahoo.com"],
    ["name"=>"Rosalba","surname"=>"Fontana","address"=>"Strada Harry 6 Appartamento 00 Sesto Raniero, 40235 Prato (IS)","email"=>"Rosalba.Fontana@yahoo.com"],
    ["name"=>"Sabino","surname"=>"Pagano","address"=>"Piazza Ricci 26 Piano 0 Quarto Neri, 11732 Rieti (RO)","email"=>"Sabino.Pagano@yahoo.com"],
    ["name"=>"Antimo","surname"=>"Orlando","address"=>"Incrocio Milani 98 Marino del friuli, 96124 Reggio Calabria (CH)","email"=>"Antimo.Orlando@yahoo.com"],
    ["name"=>"Thea","surname"=>"Amato","address"=>"Strada Rizzo 98 Appartamento 24 Santoro nell'emilia, 69820 Enna (RI)","email"=>"Thea.Amato@yahoo.com"],
    ["name"=>"Isabel","surname"=>"Mancini","address"=>"Strada Selvaggia 08 Appartamento 88 Nayade salentino, 43073 Arezzo (TE)","email"=>"Isabel.Mancini@hotmail.com"],
    ["name"=>"Elga","surname"=>"Gentile","address"=>"Strada Loris 507 Appartamento 15 Gatti del friuli, 38731 Belluno (CA)","email"=>"Elga.Gentile@yahoo.com"],
    ["name"=>"Alighieri","surname"=>"Bernardi","address"=>"Contrada Rizzo 993 Appartamento 27 San Isira, 03361 Brescia (PR)","email"=>"Alighieri.Bernardi@yahoo.com"],
    ["name"=>"Cosetta","surname"=>"Bellini","address"=>"Borgo Jole 439 Piano 5 Sanna a mare, 49575 Pavia (CS)","email"=>"Cosetta.Bellini@yahoo.com"],
    ["name"=>"Diamante","surname"=>"Leone","address"=>"Incrocio Longo 316 Appartamento 28 Lombardo umbro, 73792 Lecce (AP)","email"=>"Diamante.Leone@yahoo.com"],
    ["name"=>"Kociss","surname"=>"Rinaldi","address"=>"Rotonda Marino 61 Sesto Odino calabro, 74314 Ragusa (TA)","email"=>"Kociss.Rinaldi@yahoo.com"],
    ["name"=>"Ione","surname"=>"Fabbri","address"=>"Piazza Grasso 575 Negri salentino, 24546 Pesaro e Urbino (BT)","email"=>"Ione.Fabbri@yahoo.com"],
    ["name"=>"Enrica","surname"=>"Ferri","address"=>"Via Mazza 549 Piano 0 Milani laziale, 93604 Trieste (GE)","email"=>"Enrica.Ferri@yahoo.com"],
    ["name"=>"Tommaso","surname"=>"Conti","address"=>"Via Mariani 8 Cosetta nell'emilia, 44109 Alessandria (PO)","email"=>"Tommaso.Conti@yahoo.com"],
    ["name"=>"Marina","surname"=>"Ferrari","address"=>"Incrocio Ruth 1 Quarto Xavier calabro, 40189 Matera (CR)","email"=>"Marina.Ferrari@yahoo.com"],
    ["name"=>"Carmela","surname"=>"Ferretti","address"=>"Borgo Fatima 6 Timothy a mare, 61543 Alessandria (CN)","email"=>"Carmela.Ferretti@yahoo.com"],
    ["name"=>"Nabil","surname"=>"Russo","address"=>"Via Negri 620 Bellini umbro, 08891 Salerno (TN)","email"=>"Nabil.Russo@hotmail.com"],
    ["name"=>"Giovanna","surname"=>"Russo","address"=>"Strada Ferrara 17 Pellegrino calabro, 63271 Vicenza (PC)","email"=>"Giovanna.Russo@yahoo.com"],
    ["name"=>"Fatima","surname"=>"Gallo","address"=>"Borgo Mariani 82 Piano 7 Sesto Ione lido, 14258 Pescara (BS)","email"=>"Fatima.Gallo@yahoo.com"],
    ["name"=>"Enrica","surname"=>"Grassi","address"=>"Piazza Galli 76 San Lino, 76294 Mantova (FI)","email"=>"Enrica.Grassi@hotmail.com"],
    ["name"=>"Marieva","surname"=>"Messina","address"=>"Rotonda Rizzo 75 Piano 8 Borgo Giuliano laziale, 43234 Bologna (GO)","email"=>"Marieva.Messina@yahoo.com"],
    ["name"=>"Mauro","surname"=>"Montanari","address"=>"Incrocio Lucrezia 971 Vitale sardo, 06657 Lecce (CN)","email"=>"Mauro.Montanari@yahoo.com"],
    ["name"=>"Edvige","surname"=>"Lombardi","address"=>"Incrocio Ione 6 Piano 4 Settimo Ippolito a mare, 51538 Varese (FM)","email"=>"Edvige.Lombardi@yahoo.com"],
    ["name"=>"Sesto","surname"=>"De Angelis","address"=>"Rotonda Anselmo 067 Piano 2 Quarto Mietta a mare, 78464 Rieti (BR)","email"=>"Sesto.De Angelis@hotmail.com"],
    ["name"=>"Pericle","surname"=>"Vitale","address"=>"Incrocio Ninfa 736 Borgo Boris ligure, 03297 Nuoro (LE)","email"=>"Pericle.Vitale@hotmail.com"],
    ["name"=>"Gianmaria","surname"=>"Palmieri","address"=>"Rotonda Costantini 5 Settimo Antonio a mare, 97131 Monza e della Brianza (BT)","email"=>"Gianmaria.Palmieri@yahoo.com"],
    ["name"=>"Marzio","surname"=>"Pellegrino","address"=>"Via Lombardo 59 Caruso ligure, 23737 Catania (SP)","email"=>"Marzio.Pellegrino@yahoo.com"],
    ["name"=>"Umberto","surname"=>"Mazza","address"=>"Strada Sorrentino 029 Appartamento 59 Joannes salentino, 91954 Frosinone (AG)","email"=>"Umberto.Mazza@yahoo.com"],
    ["name"=>"Erminio","surname"=>"Coppola","address"=>"Contrada Piererminio 39 Testa umbro, 70905 Frosinone (FG)","email"=>"Erminio.Coppola@yahoo.com"],
    ["name"=>"Alberto","surname"=>"Villa","address"=>"Via Esposito 59 Piano 4 Noemi terme, 73470 Pavia (CS)","email"=>"Alberto.Villa@yahoo.com"],
    ["name"=>"Domingo","surname"=>"Longo","address"=>"Via Jarno 86 Sesto Ivano nell'emilia, 61869 Salerno (CR)","email"=>"Domingo.Longo@yahoo.com"],
    ["name"=>"Brigitta","surname"=>"Pellegrino","address"=>"Strada Vinicio 4 San Luigi, 22789 Belluno (TS)","email"=>"Brigitta.Pellegrino@yahoo.com"],
    ["name"=>"Flaviana","surname"=>"Fontana","address"=>"Contrada Rinaldi 85 San Manuele salentino, 03361 Benevento (VR)","email"=>"Flaviana.Fontana@yahoo.com"],
    ["name"=>"Maristella","surname"=>"Piras","address"=>"Contrada Pericle 254 Ferrara calabro, 37538 Chieti (VS)","email"=>"Maristella.Piras@yahoo.com"],
    ["name"=>"Sibilla","surname"=>"Santoro","address"=>"Strada Neri 19 Alighiero terme, 43238 Campobasso (CT)","email"=>"Sibilla.Santoro@yahoo.com"],
    ["name"=>"Carlo","surname"=>"Russo","address"=>"Incrocio Samira 0 Sesto Fortunata sardo, 54675 Latina (PV)","email"=>"Carlo.Russo@yahoo.com"],
    ["name"=>"Gianriccardo","surname"=>"Martinelli","address"=>"Contrada Raoul 981 Piano 2 Morelli lido, 28669 Perugia (CO)","email"=>"Gianriccardo.Martinelli@yahoo.com"],
    ["name"=>"Kociss","surname"=>"Donati","address"=>"Borgo Neri 073 Piras a mare, 70759 Barletta-Andria-Trani (SS)","email"=>"Kociss.Donati@yahoo.com"],
    ["name"=>"Gianantonio","surname"=>"Parisi","address"=>"Incrocio Lombardo 5 Diana ligure, 46811 Pisa (CL)","email"=>"Gianantonio.Parisi@yahoo.com"],
    ["name"=>"Penelope","surname"=>"Ricci","address"=>"Contrada Eliziario 0 Settimo Mariapia, 67967 Como (PO)","email"=>"Penelope.Ricci@yahoo.com"],
    ["name"=>"Emanuel","surname"=>"Pagano","address"=>"Contrada Fabbri 17 Sarita nell'emilia, 82978 Palermo (CE)","email"=>"Emanuel.Pagano@yahoo.com"],
    ["name"=>"Timoteo","surname"=>"Milani","address"=>"Strada Leone 4 Appartamento 18 Settimo Renzo, 19516 Pisa (BT)","email"=>"Timoteo.Milani@yahoo.com"],
    ["name"=>"Carlo","surname"=>"Lombardo","address"=>"Piazza Tolomeo 943 Piano 9 Quarto Hector, 79083 Cagliari (LT)","email"=>"Carlo.Lombardo@hotmail.com"],
    ["name"=>"Neri","surname"=>"De Santis","address"=>"Rotonda Morelli 017 Piano 6 Galli lido, 72941 La Spezia (PO)","email"=>"Neri.De Santis@yahoo.com"],
    ["name"=>"Radio","surname"=>"Bruno","address"=>"Piazza Lombardo 731 Appartamento 62 Settimo Ortensia ligure, 19492 Sassari (TP)","email"=>"Radio.Bruno@yahoo.com"],
    ["name"=>"Edipo","surname"=>"Moretti","address"=>"Borgo Artemide 3 Settimo Rosalino, 22105 Salerno (CR)","email"=>"Edipo.Moretti@hotmail.com"],
    ["name"=>"Selvaggia","surname"=>"Costa","address"=>"Strada Rossi 383 Piano 4 Galli ligure, 88327 Latina (PN)","email"=>"Selvaggia.Costa@yahoo.com"],
    ["name"=>"Lisa","surname"=>"Damico","address"=>"Incrocio Emilia 4 Fontana umbro, 35995 Lecco (NO)","email"=>"Lisa.Damico@yahoo.com"],
    ["name"=>"Miriam","surname"=>"Gatti","address"=>"Rotonda Marino 932 Appartamento 44 Borgo Michael a mare, 30796 Benevento (BA)","email"=>"Miriam.Gatti@yahoo.com"],
    ["name"=>"Tazio","surname"=>"Grassi","address"=>"Via Parisi 88 San Liborio a mare, 57734 Venezia (MI)","email"=>"Tazio.Grassi@hotmail.com"],
    ["name"=>"Jelena","surname"=>"Ricci","address"=>"Borgo Edilio 892 Modesto salentino, 10261 Venezia (MT)","email"=>"Jelena.Ricci@yahoo.com"],
    ["name"=>"Sasha","surname"=>"Ruggiero","address"=>"Rotonda Maria 8 Appartamento 25 Marieva laziale, 94311 Latina (SA)","email"=>"Sasha.Ruggiero@yahoo.com"],
    ["name"=>"Felicia","surname"=>"Mariani","address"=>"Borgo Sebastian 33 Borgo Jack, 36813 Medio Campidano (SP)","email"=>"Felicia.Mariani@yahoo.com"],
    ["name"=>"Selvaggia","surname"=>"Ferraro","address"=>"Piazza Silverio 002 Piano 1 Testa lido, 09320 Belluno (BR)","email"=>"Selvaggia.Ferraro@yahoo.com"],
    ["name"=>"Clodovea","surname"=>"Fabbri","address"=>"Via Silvestri 92 Piano 0 Mariapia terme, 80291 Gorizia (VS)","email"=>"Clodovea.Fabbri@hotmail.com"],
    ["name"=>"Rufo","surname"=>"Riva","address"=>"Strada Nestore 379 Appartamento 78 Akira nell'emilia, 76943 Bologna (LE)","email"=>"Rufo.Riva@yahoo.com"],
];

$i = 1;
foreach ($users as $user) {
    $db->insert('user', $user);
    $i++;
}

echo "Importati $i utenti" . PHP_EOL;
